### PR TITLE
Simplify signup so that services can immediately configure everything

### LINKED ISSUE #1583: Simplified signup
- After signup (/customers/signup), send confirmation email
- The link in the confirmation email should open a page where they can set their password
- After setting their password, redirect to the dashboard. They can modify everything without the city needing to do anything.
- After setting their password, notify the city of a new signup
- City can accept or deny the signup. Denying will permanently set the service to invisible and being unable to send news as a result.
- City should have a list of all 'denied' services so they can still set 'accept' them afterwards (for when they made a mistake)

### PR DESCRIPTION
**Pull request by lucasvanhalst**
This eliminates the need of having to wait for the city to accept their request

Closes #1583 

### REMARKS (release a TEST version before going LIVE)
- Needs testing and review of Tom
- Needs documentation from Thijs

### CODE REVIEW

**Comment by RubenMattan** [comment]
Why are there 2 addresses in signup?
Because i don't see where the service address is used, in the shop customer the user address is used

**Comment by RubenMattan** [comment]
on my dev env creating news was possible however it was not visible to the user and he did not receive any notification (through news review of city app)

**Comment by RubenMattan** [comment]
Ok now it's impossible, to create news when the city has denied you, however its still possible to create news when you are invisible.

Also i would just show the error when the user tried to create a news item and not when he goes to news & actions

**Comment by lucasvanhalst** [comment]
That sounds  a bit annoying, imagine they spent 15 minutes to create a message only to be greeted by an error

**Comment by RubenMattan** [comment]
> That sounds a bit annoying, imagine they spent 15 minutes to create a message only to be greeted by an error

When they click create not publish

**Comment by RubenMattan** [comment]
TBD:
- block signup for same emails
- also send email for already registered emails

**Pull request merged**
