### PR TITLE
Qmatic

### PR DESCRIPTION
**Pull request by RubenMattan**
Needs https://github.com/our-city-app/mobicage-android-client/pull/181 + same implementation on iOS

Screenshot 2019-10-16 at 12 04 32

Screenshot 2019-10-16 at 12 05 22

### CODE REVIEW

**Comment by bart-at-mobicage** [comment]
iOS is done. 
Tested with PSP. 
Needs to be tested with Q-Matic.

https://github.com/our-city-app/mobicage-ios-client/pull/159

**Comment by bart-at-mobicage** [comment]
What's the procedure to enable Q-Matic for a service? Going to service panel and creating a menu item for the embedded app? Might be useful to automate this and create a module for it.

**Comment by lucasvanhalst** [comment]
Nothing yet, adding a module for q-matic seems like a good idea. we'd have to make a page with those settings as well since there's nothing for that yet.

**Comment by lucasvanhalst** [comment]
@bart-at-mobicage updated with the following:
- Add module to enable / disable the integration, which creates a menu item to book appointments
- Add UI for configuring the q-matic server url and token

**Comment by bart-at-mobicage** [comment]
Suggestion to move the code of `solutions.common.bizz.forms.poke_forms` to mobicage-backend. Whenever there's a poke call for a service menu item with an embeddedApp property or a form_id property, respond with 'You need to update the app to use this feature.'

**Pull request merged**
