### PR TITLE
Polls

### LINKED ISSUE #1150: Poll
Making polls in our Dashboard.
For this we need to add this as a feature.  Logo: https://fontawesome.com/v4.7.0/icon/list-ul

1) choose your type of poll
Vote (nl: "stemming") --> for this you can use the code of the Hoeilaart poll - you can integrate this in OSA. https://github.com/our-city-app/plugin-light-parade
Here you can only vote for eg top 5 / top 3 / number one choice 
Poll (nl:"enquête") --> for this we will base ourselves on google forms. 
Goal: merchant can enter questions + each question needs to have a specific type of answer
answer types: 	
- multiple choice
- checkboxes
- short answer text (= open answer)
- lang answer text (= open answer)

2) In Dashboard people need to be able to see previous, current and pending polls and need to be able to make a new poll (when clicking on ‘make a new poll’ they need to have the 2 choices as stated above)

Eg: 
image

 
Make 3 subcategories: 
 	1. Pending polls
	→ name of poll + icons: start (), edit (), trash can () 
	2. current polls 
	→ name of poll + 2 icons: stop(), see results (), trash can () 
3. Previous polls
	→ name of poll + 2 icons: see results (), trash can () 
image

3) For the results 
     → graph/table to represent the results

### PR DESCRIPTION
**Pull request by abom**
- Added polls solution module

- [ ] Translations (update EN, add NL)
- [ ] Add poll functionality description and image
- [ ] Set the queue to polls pipeline[ other than the default](https://github.com/our-city-app/oca-backend/pull/1183/files#diff-c612fa016c2be3027c170ab2895e5300R42)
- [x] Auto-close polls on ends_on date (add a cron)
- [x] Create a branding to replace the flow completely (as described at https://github.com/our-city-app/oca-backend/issues/1150#issuecomment-444128256)
- [x] A pipeline to aggregate poll answers
- [x] Results notifications job/cron

Closes #1150.

Related (need to be merged first)
https://github.com/our-city-app/mobicage-backend/pull/143

### CODE REVIEW

**Comment by RubenMattan** [comment]
Few comments:
- PollAnswer key should be like this `ndb.Key(cls, poll_id, parent=parent_ndb_key(app_user))`
- PollRegister can be deleted
- Polls is not visible in functionalities
- Question should not extend from polymodel but should be like below
- Poll should not extend from polymodel also let google create an id instead of using allocate_ids
- For now only show results as a graph not as a list
- i don't like the sharding counter. I know Bart did it this way. But instead we are going to do the following. No results are shown until the poll has ended. When it has ended the status of the poll changed the processing. This will start a pipeline to loop over every PollAnswer and save the result on Poll.questions.choices.count

```
class Choice(NdbModel):
    text = ndb.StringProperty(indexed=False)
    count = ndb.IntegerProperty(indexed=False)
    
class Question(NdbModel):
    answer_type = ndb.StringProperty(indexed=False)
    text = ndb.StringProperty(indexed=False)
    choices = ndb.LocalStructuredProperty(Choice, repeated=True)
    optional = ndb.BooleanProperty(indexed=False, default=False)
```

**Comment by abom** [comment]
> Don't show 3 tabs 'pending', 'running' and 'completed' Show 1 list with an extra label next to the title

No problem, this what was requested in #1150, this list would also have the same buttons to start/stop delete different polls with different status?

> PollAnswer key should be like this ndb.Key(cls, poll_id, parent=parent_ndb_key(app_user))
> PollRegister can be deleted

I thought of one thing, polls should be **anonymous**, even we service admins shouldn't be able to correlate a user answer to a poll with anything, that's why there're two different models, one for storing the answer itself, and another one acts like a register.

> Polls is not visible in functionalities

Will add it.

> Question should not extend from polymodel but should be like below
> Poll should not extend from polymodel also let google create an id instead of using allocate_ids

I don't know what it's the problem of using a polymodel actually, but this would save as passing/storing question type every time, also different question types may have different data (like multiple choice question should has some choices, but the short text answer question not).

In the start, we want more question types than ones with choices, hence using the polymodel  (knowing there would be other solutions).

> i don't like the sharding counter. I know Bart did it this way. But instead we are going to do the following. No results are shown until the poll has ended. When it has ended the status of the poll changed the processing. This will start a pipeline to loop over every PollAnswer and save the result on Poll.questions.choices.count

This is also a decision made from the start because in #1150 and my talks with @bart-at-mobicage, it was intended to show results anytime after the poll starts.

Also, IMHO, i don't see any difference or gains for using a pipeline to loop over all PollAnswer instead of using counter shards. I don't know for sure how pipelines will solve the write operation contention on Choice model.

**Comment by RubenMattan** [comment]
1.
- pending items have a start and delete button
- running items only have a stop button
- completed items only have a stats button

2. 
polls are anonymous to services but not to us (at least for now)

3.
i would only use polymodels if needed. The only options we will support are single and multi select. so no need to use polymodels. This is still future proof

4.
i known bart wrote the feature like this. But we don't want to show results during the poll otherwise they would never close it.

Sharding should be used for general counters not / answer / question / poll. This will create to many useless models.
A pipeline will gather all the data and only do 1 put

**Comment by abom** [comment]
PollAnswer itself was created to just list the results of a poll, not to for counting!

**Comment by RubenMattan** [comment]
> PollAnswer itself was created to just list the results of a poll, not for counting!
> We only need counting now?

We need both, and yes poll answer will be used for counting when poll has ended (only once)

**Comment by abom** [comment]
> Polls is not visible in functionalities

@RubenMattan I need the image and description...etc

**Comment by RubenMattan** [comment]
> > Polls is not visible in functionalities
> 
> @RubenMattan I need the image and description...etc

For now just copy an image of another module and description is 'polls description'
In description of the pull request mention we need to change this.

**Pull request closed without merging**
